config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  resources :products do
    resources :reviews
  end
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :title, :description, :country, :presence => true

  scope :most_reviewed_products, -> {
    select("products.id, products.title, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(3)
    }

  scope :three_most_recently_added, -> {
    order(:created_at => :desc).limit(3)
  }

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates :review_title, :review_description, :rating, :presence => true
  validates :review_description, length: { minimum: 50 }
  validates :review_description, length: { maximum: 250 }
  validates :rating, numericality: { greater_than_or_equal_to: 1 }
  validates :rating, numericality: { less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @reviews = Review.all
    @three_most_recently_added = Product.three_most_recently_added
    @most_reviewed_products = Product.most_reviewed_products
    render :index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted!"
    redirect_to products_path
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :country)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @product.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def index
    @products = Product.all
    render :index
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end

  private
  def review_params
    params.require(:review).permit(:review_title, :review_description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<h1 class="home-head">Contact</h1>

<section class="info-box">
  <p class="home-text__item">Thanks for checking out this site! Unfortunately, Northwest Coffee Company is not a real establishment. Luckily, the visionary behind this site is alive, well, and looking for a job in the tech industry!</p>
  <p class="home-text__item">If you'd like to keep the dreams of NWCC (and the dreams of an aspiring developer) alive, please feel free to contact Masen Matthews at masenmatthews@gmail.com</p>
  <p class="home-text__item">Interested in finding out more? Feel free to take a look through at following materials:<p>

  <h5 class="home-text__item"><a href="https://github.com/masenmatthews">Github</a></h5>
  <h5 class="home-text__item"><a href="https://www.linkedin.com/in/masen-matthews-codes/">LinkedIn</a></h5>
  <h5 class="home-text__item"><a href="https://www.meetup.com/pdxFLIT-Portland-Future-Leaders-In-Tech/">Meetup</a></h5>
</section>

app/views/home/index.html.erb
<section class="home-head">
  <h1 class="home-head">Northwest Coffee Company</h1>
</section>

<section class="home-text">
  <p class="home-text__item">Welcome to Northwest Coffee Company! We offer a wide variety of unique coffees. This marketplace carries everything from exotic, imported speciality coffees to simple dark roasts that were produced here in the USA. Feel free to take a look around!</p>

  <p class="home-text__item">All of our products are responsibily sourced and we work closely with all of our suppliers to ensure that everything fits our standards. If you would like to navigate through our current offerings, feel free to navigate to the "products" section of the website, which can be found at the top of this page.</p>
</section>

<section class="info-box col-sm-6">
  <h3 class="home-text__item"> Most reviewed products: </h3>

  <% @most_reviewed_products.each do |product| %>
      <p class="home-text__item">
      <%= link_to product.title, product_path(product) %>
    </p>
  <% end %>
</section>

<section class="info-box col-sm-6">
  <h3 class="home-text__item"> Three most recently added products </h3>

  <% @three_most_recently_added.each do |product| %>
      <p class="home-text__item">
      <%= link_to product.title, product_path(product) %>
    </p>
  <% end %>
</section>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <p>There was a problem! Please correct these errors before continuing:</p>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div>
        <div class="navbar-brand"><%= link_to "NWCC", root_path %></div>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="main-nav__item">
          <%= link_to "Products", products_path %>
        </li>
        <li class="main-nav__item">
          <%= link_to "Contact", contacts_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Northwest Quality Coffee Products</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
    <%= render 'layouts/navbar' %>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1 class="home-head">Edit product</h1>

<section class="info-box">
  <br>
  <%= render "layouts/form" %>
  <p><%= link_to "Delete", product_path(@product),
    :data =>
      {:confirm => "Are you sure?",
       :method => "delete"} %></p>
  <p><%= link_to "Return to product page", product_path %><p>
</section>

app/views/products/index.html.erb
<h1 class="home-head">Products</h1>

<ul class="product-list">
  <% @products.each do |single_product| %>
    <li><%= link_to single_product.title, product_path(single_product) %> | <%= single_product.description %></li>
  <% end %>
</ul>

<p><%= link_to "Add new product", new_product_path %></p>

app/views/products/new.html.erb
<h1 class="home-head">New Product</h1>

<section class="info-box">
<%= render "layouts/form" %>
</section>

app/views/products/show.html.erb
<h1 class="home-head"><%= @product.title %></h1>
<h3 class="home-head">Made in <%= @product.country %> </h3>

<p><%= link_to "Edit product", edit_product_path(@product) %></p>
<p><%= link_to "Return to products", products_path %></p>
<p><%= link_to "Add new review", new_product_review_path(@product) %></p>
<%= button_to "Delete product", {:controller => :products,
      :action => 'destroy', :id => @product.id }, :method => :delete %>


<section class="info-box">
  <h3 class="detail-head">See what people are saying about <%= @product.title %>: </h3>
  <% if @product.reviews.any? %>
    <ul>
      <% @product.reviews.each do |review| %>
        <li>
            <h3>Rating: <%= review.rating %></h3>
            <h3>Review: <%= review.review_title %></h3>

          <!-- <%=link_to "Edit review", edit_product_review_path(@product, review) %> | -->

          <!-- delete function not working - commenting out for now -->

          <!-- <%=link_to "Delete", product_review_path(@product, review),
            :data => {:confirm => "Are you sure?", :method => "delete"} %> -->
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No reviews - help improve our site by adding one!</p>
  <% end %>
</section>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<section class="info-box">
<br>
<%= form_for [@product, @review] do |f| %>
  <%= f.label :review_title %>
  <%= f.text_field :review_title %>
  <%= f.label :review_description %>
  <%= f.text_field :review_description %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <p><%= f.submit %></p>
<% end %>
</section>

app/views/reviews/edit.html.erb
<h1 class="home-head">Edit review</h1>

<%= render "form" %>

app/views/reviews/index.html.erb
<ul>
  <% @products.each do |single_product| %>
    <li><%= link_to single_product.name, edit_product_path(single_product) %></li>
    <%= single_product.description %>
  <% end %>
</ul>

<p><%= link_to "Add new product", new_product_path %></p>

app/views/reviews/new.html.erb
<h1 class="home-head">New review for <%= @product.title %></h1>

<%= render 'form' %>